language: python

matrix:
  include:
  - python: 3.6
    env: TEST_TYPE="flake8"
  - python: 3.6
    env: TEST_TYPE="rtd"
  - python: 2.7
    env: TEST_TYPE="pytest"
  - python: 3.4
    env: TEST_TYPE="pytest"
  - python: 3.5
    env: TEST_TYPE="pytest"
  - python: 3.6
    env: TEST_TYPE="pytest" PYPI_DEPLOY=true
  allow_failures:
  - python: 3.4
    env: TEST_TYPE="pytest"
  - python: 3.5
    env: TEST_TYPE="pytest"

before_install:
  - pip install -U pip setuptools wheel

install:
  - |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      travis_wait pip install -r test_requirements.txt
      travis_wait pip install .
      pip install --quiet coverage
      pip install --quiet coveralls
    fi
  - |
    if [[ "$TEST_TYPE" == "flake8" ]]; then
      pip install "flake8(>=3.7,<3.8)"
    fi
  - |
    if [[ "$TEST_TYPE" == "rtd" ]]; then
      travis_wait pip install -r test_requirements.txt
      travis_wait pip install .
      pip install sphinx
    fi

script:
- if [[ "$TEST_TYPE" == "pytest" ]]; then pytest -v --cov=jsonextended --cov-report= jsonextended ; fi
- if [[ "$TEST_TYPE" == "flake8" ]]; then flake8 . ; fi
- if [[ "$TEST_TYPE" == "rtd" ]]; then cd docs; make ; fi

after_success:
  - if [[ "$TEST_TYPE" == "pytest" ]]; then coveralls ; fi

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: "cjsewell"
    password:
      secure: KhgfNkJaHD7CDI49Wbz16b78SGuM9ROTDrk2kqILXWBohKPe6N6RAYMDSRkJldmCG3/ryg5QMOU38HLqnkFA2cNoBt1TShrF7nsVIXdKEsRnQDynXqnSXRrQ4mGIlEnOjcWUPL8t7y1t1+4qjHH3rBVojgR3dsfKTJSKF7lhd7MpWoOhh7u2tRQHqIp3jteqDlh4EpTp/9ClOjTOcUl2w4NgOUr64h8cseXV4YZPhhMrLGr1gKYLaPY8btkm2iSI8p0Vm4tuSyNLQTT73mrEVHAfSNZQT+wFRgA5xaP8FVescdd9ftotbbgsIeh7Ke464n/5htWSfurrQUc4ZQNtUTDj5riD4BVtdBz1T9tFbn+w93b/v/dO5XJKObj3n1oG3w0iBnlfl6obGyb46Y6FsmMt+sYYC67EgFeulJaAKPiF3OSZvEpE/zgvqNLVG2SbrPmLj/TPGqoQA3fNXQdoqmldLrliq5FqvruNPprsMrf9tDV2E/mIMuAQDWgtTRCEkdZallP2Cyj7zFLB9FQJ8qepwselUWoAAvvoaFgNRSFfcCQQgZ3MU465g01bXYmRKynCeksD/stmn78fSkVnZdxoBrjTLxgyS8XSAOlOmMzd0iNfrmi2AgiyCnO9vfHWV7vPjEO6Ui5Q6Uc6D0k30d0/dzJt7sxtJWLMfV2lDmE=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
